connect placement api
anurag629/IET_AGRA pull request #1
Opened 2023-10-12 04:57 UTC by tech-bash

2023-10-12 05:14 UTC, anurag629 requested changes
Use RTK Query from Redux Toolkit, just as we did for [AUTH](https://github.com/anurag629/IET_AGRA/blob/main/src/services/userAuthApi.js), to maintain the project structure.

2023-10-12 05:14 UTC, anurag629 commented on src/components/TandPCell/CellComponent/Placements.js
@tech-bash do not change the current CSS

2023-10-12 05:31 UTC, tech-bash commented on src/components/TandPCell/CellComponent/Placements.js
Ok

2023-10-12 05:36 UTC, tech-bash commented
> Use RTK Query from Redux Toolkit, just as we did for [AUTH](https://github.com/anurag629/IET_AGRA/blob/main/src/services/userAuthApi.js), to maintain the project structure.

ok

2023-10-17 09:13 UTC, tech-bash reviewed
Resolved

2023-10-17 09:46 UTC, anurag629 approved these changes
lgtm

2023-10-17 09:46 UTC, anurag629 commented on src/components/TandPCell/CellComponent/Placements.js
> +                <Table>
@tech-bash do not change the UI of the table, use same table

2023-10-17 09:47 UTC, merged